# Docker-Compose Datei f√ºr Tontastika Anwendung
# Definiert die Services, Docker baut nach dieser Konfiguration die Container

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: tontastika_mysql
    restart: unless-stopped
    env_file:
      - server/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tontastika_network

  # Node.js Express Backend
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: tontastika_app
    restart: unless-stopped
    env_file:
      - server/.env
    environment:
    # db ist hier kein Variablenname sondern der name des MySQL Services im Docker-Compose Netzwerk
      MYSQL_HOST: db
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - uploads_data:/app/uploads
    depends_on:
      - db
    networks:
      - tontastika_network

  # Adminer - Database GUI
  adminer:
    image: adminer:latest
    container_name: tontastika_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - tontastika_network

volumes:
  mysql_data:
  uploads_data:

networks:
  tontastika_network:
    driver: bridge
