# Docker-Compose Datei f체r Tontastika Anwendung
# Definiert die Services, Docker baut nach dieser Konfiguration die Container

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: tontastika_mysql
    restart: unless-stopped
    env_file:
      - server/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # pr체ft alle 5 Sekunden(interval) ob die DB erreichbar ist, bis sie als "healthy" gilt, also erreichbar ist.
    # dies wird 5 mal (retries) versucht. Jeder dieser Healthtest l채uft f체r 3 Sekunden(timeout).
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
    networks:
      - tontastika_network

  # Node.js Express Backend
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: tontastika_app
    restart: unless-stopped
    env_file:
      - server/.env
    environment:
    # db ist hier kein Variablenname sondern der name des MySQL Services im Docker-Compose Netzwerk
      MYSQL_HOST: db
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - uploads_data:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tontastika_network

  # Adminer - Database GUI
  adminer:
    image: adminer:latest
    container_name: tontastika_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - tontastika_network

volumes:
  mysql_data:
  uploads_data:

networks:
  tontastika_network:
    driver: bridge
